// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: LinkAttributionProto/api_key.proto

package linkAttribution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiKeyGetCurrentKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationUnid string `protobuf:"bytes,1,opt,name=organizationUnid,proto3" json:"organizationUnid,omitempty"`
	AppUnid          string `protobuf:"bytes,2,opt,name=appUnid,proto3" json:"appUnid,omitempty"`
}

func (x *ApiKeyGetCurrentKeyRequest) Reset() {
	*x = ApiKeyGetCurrentKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_api_key_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiKeyGetCurrentKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyGetCurrentKeyRequest) ProtoMessage() {}

func (x *ApiKeyGetCurrentKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_api_key_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyGetCurrentKeyRequest.ProtoReflect.Descriptor instead.
func (*ApiKeyGetCurrentKeyRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKeyGetCurrentKeyRequest) GetOrganizationUnid() string {
	if x != nil {
		return x.OrganizationUnid
	}
	return ""
}

func (x *ApiKeyGetCurrentKeyRequest) GetAppUnid() string {
	if x != nil {
		return x.AppUnid
	}
	return ""
}

type ApiKeyGetCurrentKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *ApiKeyGetCurrentKeyResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32                             `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ApiKeyGetCurrentKeyResponse) Reset() {
	*x = ApiKeyGetCurrentKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_api_key_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiKeyGetCurrentKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyGetCurrentKeyResponse) ProtoMessage() {}

func (x *ApiKeyGetCurrentKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_api_key_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyGetCurrentKeyResponse.ProtoReflect.Descriptor instead.
func (*ApiKeyGetCurrentKeyResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_api_key_proto_rawDescGZIP(), []int{1}
}

func (x *ApiKeyGetCurrentKeyResponse) GetData() *ApiKeyGetCurrentKeyResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiKeyGetCurrentKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiKeyGetCurrentKeyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ApiKeyGenerateKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApiKeyGenerateKeyRequest) Reset() {
	*x = ApiKeyGenerateKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_api_key_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiKeyGenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyGenerateKeyRequest) ProtoMessage() {}

func (x *ApiKeyGenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_api_key_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyGenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*ApiKeyGenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_api_key_proto_rawDescGZIP(), []int{2}
}

type ApiKeyGenerateKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *ApiKeyGenerateKeyResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32                           `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ApiKeyGenerateKeyResponse) Reset() {
	*x = ApiKeyGenerateKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_api_key_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiKeyGenerateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyGenerateKeyResponse) ProtoMessage() {}

func (x *ApiKeyGenerateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_api_key_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyGenerateKeyResponse.ProtoReflect.Descriptor instead.
func (*ApiKeyGenerateKeyResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_api_key_proto_rawDescGZIP(), []int{3}
}

func (x *ApiKeyGenerateKeyResponse) GetData() *ApiKeyGenerateKeyResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiKeyGenerateKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiKeyGenerateKeyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ApiKeyGetCurrentKeyResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unid      string                 `protobuf:"bytes,1,opt,name=unid,proto3" json:"unid,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	Key       string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Secret    string                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *ApiKeyGetCurrentKeyResponse_Data) Reset() {
	*x = ApiKeyGetCurrentKeyResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_api_key_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiKeyGetCurrentKeyResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyGetCurrentKeyResponse_Data) ProtoMessage() {}

func (x *ApiKeyGetCurrentKeyResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_api_key_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyGetCurrentKeyResponse_Data.ProtoReflect.Descriptor instead.
func (*ApiKeyGetCurrentKeyResponse_Data) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_api_key_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ApiKeyGetCurrentKeyResponse_Data) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *ApiKeyGetCurrentKeyResponse_Data) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApiKeyGetCurrentKeyResponse_Data) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ApiKeyGetCurrentKeyResponse_Data) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *ApiKeyGetCurrentKeyResponse_Data) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ApiKeyGetCurrentKeyResponse_Data) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ApiKeyGenerateKeyResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ApiKeyGenerateKeyResponse_Data) Reset() {
	*x = ApiKeyGenerateKeyResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_api_key_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiKeyGenerateKeyResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyGenerateKeyResponse_Data) ProtoMessage() {}

func (x *ApiKeyGenerateKeyResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_api_key_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyGenerateKeyResponse_Data.ProtoReflect.Descriptor instead.
func (*ApiKeyGenerateKeyResponse_Data) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_api_key_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ApiKeyGenerateKeyResponse_Data) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_LinkAttributionProto_api_key_proto protoreflect.FileDescriptor

var file_LinkAttributionProto_api_key_proto_rawDesc = []byte{
	0x0a, 0x22, 0x4c, 0x69, 0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x50, 0x6b, 0x67, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x62, 0x0a, 0x1a, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70,
	0x70, 0x55, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70,
	0x55, 0x6e, 0x69, 0x64, 0x22, 0x81, 0x03, 0x0a, 0x1b, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x50, 0x6b, 0x67, 0x2e, 0x41,
	0x70, 0x69, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x1a, 0xf2, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x64,
	0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x41, 0x70, 0x69, 0x4b,
	0x65, 0x79, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x19, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x50, 0x6b, 0x67, 0x2e, 0x41, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x1a,
	0x18, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32, 0xc2, 0x02, 0x0a, 0x0d, 0x41, 0x70,
	0x69, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x13, 0x41,
	0x70, 0x69, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4b,
	0x65, 0x79, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x50, 0x6b, 0x67, 0x2e, 0x41,
	0x70, 0x69, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x4b,
	0x65, 0x79, 0x50, 0x6b, 0x67, 0x2e, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x74, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x13, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x50, 0x6b, 0x67, 0x2e, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x50, 0x6b, 0x67, 0x2e, 0x41, 0x70, 0x69, 0x4b,
	0x65, 0x79, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x16, 0x41, 0x70, 0x69, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x50, 0x6b, 0x67, 0x2e, 0x41, 0x70,
	0x69, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x50,
	0x6b, 0x67, 0x2e, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a,
	0x5a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_LinkAttributionProto_api_key_proto_rawDescOnce sync.Once
	file_LinkAttributionProto_api_key_proto_rawDescData = file_LinkAttributionProto_api_key_proto_rawDesc
)

func file_LinkAttributionProto_api_key_proto_rawDescGZIP() []byte {
	file_LinkAttributionProto_api_key_proto_rawDescOnce.Do(func() {
		file_LinkAttributionProto_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(file_LinkAttributionProto_api_key_proto_rawDescData)
	})
	return file_LinkAttributionProto_api_key_proto_rawDescData
}

var file_LinkAttributionProto_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_LinkAttributionProto_api_key_proto_goTypes = []interface{}{
	(*ApiKeyGetCurrentKeyRequest)(nil),       // 0: apiKeyPkg.ApiKeyGetCurrentKeyRequest
	(*ApiKeyGetCurrentKeyResponse)(nil),      // 1: apiKeyPkg.ApiKeyGetCurrentKeyResponse
	(*ApiKeyGenerateKeyRequest)(nil),         // 2: apiKeyPkg.ApiKeyGenerateKeyRequest
	(*ApiKeyGenerateKeyResponse)(nil),        // 3: apiKeyPkg.ApiKeyGenerateKeyResponse
	(*ApiKeyGetCurrentKeyResponse_Data)(nil), // 4: apiKeyPkg.ApiKeyGetCurrentKeyResponse.Data
	(*ApiKeyGenerateKeyResponse_Data)(nil),   // 5: apiKeyPkg.ApiKeyGenerateKeyResponse.Data
	(*timestamppb.Timestamp)(nil),            // 6: google.protobuf.Timestamp
}
var file_LinkAttributionProto_api_key_proto_depIdxs = []int32{
	4, // 0: apiKeyPkg.ApiKeyGetCurrentKeyResponse.data:type_name -> apiKeyPkg.ApiKeyGetCurrentKeyResponse.Data
	5, // 1: apiKeyPkg.ApiKeyGenerateKeyResponse.data:type_name -> apiKeyPkg.ApiKeyGenerateKeyResponse.Data
	6, // 2: apiKeyPkg.ApiKeyGetCurrentKeyResponse.Data.createdAt:type_name -> google.protobuf.Timestamp
	6, // 3: apiKeyPkg.ApiKeyGetCurrentKeyResponse.Data.updatedAt:type_name -> google.protobuf.Timestamp
	6, // 4: apiKeyPkg.ApiKeyGetCurrentKeyResponse.Data.deletedAt:type_name -> google.protobuf.Timestamp
	0, // 5: apiKeyPkg.ApiKeyService.ApiKeyGetCurrentKey:input_type -> apiKeyPkg.ApiKeyGetCurrentKeyRequest
	2, // 6: apiKeyPkg.ApiKeyService.ApiKeyReGenerateKey:input_type -> apiKeyPkg.ApiKeyGenerateKeyRequest
	2, // 7: apiKeyPkg.ApiKeyService.ApiKeyReGenerateSecret:input_type -> apiKeyPkg.ApiKeyGenerateKeyRequest
	1, // 8: apiKeyPkg.ApiKeyService.ApiKeyGetCurrentKey:output_type -> apiKeyPkg.ApiKeyGetCurrentKeyResponse
	3, // 9: apiKeyPkg.ApiKeyService.ApiKeyReGenerateKey:output_type -> apiKeyPkg.ApiKeyGenerateKeyResponse
	3, // 10: apiKeyPkg.ApiKeyService.ApiKeyReGenerateSecret:output_type -> apiKeyPkg.ApiKeyGenerateKeyResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_LinkAttributionProto_api_key_proto_init() }
func file_LinkAttributionProto_api_key_proto_init() {
	if File_LinkAttributionProto_api_key_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_LinkAttributionProto_api_key_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiKeyGetCurrentKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_api_key_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiKeyGetCurrentKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_api_key_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiKeyGenerateKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_api_key_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiKeyGenerateKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_api_key_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiKeyGetCurrentKeyResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_api_key_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiKeyGenerateKeyResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LinkAttributionProto_api_key_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_LinkAttributionProto_api_key_proto_goTypes,
		DependencyIndexes: file_LinkAttributionProto_api_key_proto_depIdxs,
		MessageInfos:      file_LinkAttributionProto_api_key_proto_msgTypes,
	}.Build()
	File_LinkAttributionProto_api_key_proto = out.File
	file_LinkAttributionProto_api_key_proto_rawDesc = nil
	file_LinkAttributionProto_api_key_proto_goTypes = nil
	file_LinkAttributionProto_api_key_proto_depIdxs = nil
}
