// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: LinkAttributionProto/app.proto

package linkAttribution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppUpsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unid       string                 `protobuf:"bytes,1,opt,name=unid,proto3" json:"unid,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deleted_At *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_At,json=deletedAt,proto3" json:"deleted_At,omitempty"`
}

func (x *AppUpsert) Reset() {
	*x = AppUpsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUpsert) ProtoMessage() {}

func (x *AppUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUpsert.ProtoReflect.Descriptor instead.
func (*AppUpsert) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{0}
}

func (x *AppUpsert) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *AppUpsert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AppUpsert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AppUpsert) GetDeleted_At() *timestamppb.Timestamp {
	if x != nil {
		return x.Deleted_At
	}
	return nil
}

type AppUpsertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *AppUpsert `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32      `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AppUpsertResponse) Reset() {
	*x = AppUpsertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppUpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUpsertResponse) ProtoMessage() {}

func (x *AppUpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUpsertResponse.ProtoReflect.Descriptor instead.
func (*AppUpsertResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppUpsertResponse) GetData() *AppUpsert {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppUpsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppUpsertResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AppUpsertListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []*AppUpsert `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Message string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32        `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AppUpsertListResponse) Reset() {
	*x = AppUpsertListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppUpsertListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUpsertListResponse) ProtoMessage() {}

func (x *AppUpsertListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUpsertListResponse.ProtoReflect.Descriptor instead.
func (*AppUpsertListResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{2}
}

func (x *AppUpsertListResponse) GetData() []*AppUpsert {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppUpsertListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppUpsertListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AppCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationUnid string `protobuf:"bytes,1,opt,name=organizationUnid,proto3" json:"organizationUnid,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Timezone         string `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *AppCreateRequest) Reset() {
	*x = AppCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppCreateRequest) ProtoMessage() {}

func (x *AppCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppCreateRequest.ProtoReflect.Descriptor instead.
func (*AppCreateRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{3}
}

func (x *AppCreateRequest) GetOrganizationUnid() string {
	if x != nil {
		return x.OrganizationUnid
	}
	return ""
}

func (x *AppCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppCreateRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type AppListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationUnid string `protobuf:"bytes,1,opt,name=organizationUnid,proto3" json:"organizationUnid,omitempty"`
}

func (x *AppListRequest) Reset() {
	*x = AppListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListRequest) ProtoMessage() {}

func (x *AppListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListRequest.ProtoReflect.Descriptor instead.
func (*AppListRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{4}
}

func (x *AppListRequest) GetOrganizationUnid() string {
	if x != nil {
		return x.OrganizationUnid
	}
	return ""
}

type AppListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []*AppListResponse_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Message string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32                   `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AppListResponse) Reset() {
	*x = AppListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListResponse) ProtoMessage() {}

func (x *AppListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListResponse.ProtoReflect.Descriptor instead.
func (*AppListResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{5}
}

func (x *AppListResponse) GetData() []*AppListResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AppDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unid             string `protobuf:"bytes,1,opt,name=unid,proto3" json:"unid,omitempty"`
	OrganizationUnid string `protobuf:"bytes,2,opt,name=organizationUnid,proto3" json:"organizationUnid,omitempty"`
}

func (x *AppDetailRequest) Reset() {
	*x = AppDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDetailRequest) ProtoMessage() {}

func (x *AppDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDetailRequest.ProtoReflect.Descriptor instead.
func (*AppDetailRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{6}
}

func (x *AppDetailRequest) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *AppDetailRequest) GetOrganizationUnid() string {
	if x != nil {
		return x.OrganizationUnid
	}
	return ""
}

type AppDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *AppDetailResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32                   `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AppDetailResponse) Reset() {
	*x = AppDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDetailResponse) ProtoMessage() {}

func (x *AppDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDetailResponse.ProtoReflect.Descriptor instead.
func (*AppDetailResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{7}
}

func (x *AppDetailResponse) GetData() *AppDetailResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppDetailResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AppDetailByDomainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainName string `protobuf:"bytes,1,opt,name=domainName,proto3" json:"domainName,omitempty"`
}

func (x *AppDetailByDomainRequest) Reset() {
	*x = AppDetailByDomainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDetailByDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDetailByDomainRequest) ProtoMessage() {}

func (x *AppDetailByDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDetailByDomainRequest.ProtoReflect.Descriptor instead.
func (*AppDetailByDomainRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{8}
}

func (x *AppDetailByDomainRequest) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

type AppListResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unid       string                 `protobuf:"bytes,1,opt,name=unid,proto3" json:"unid,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deleted_At *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_At,json=deletedAt,proto3" json:"deleted_At,omitempty"`
	Name       string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Timezone   string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *AppListResponse_Data) Reset() {
	*x = AppListResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppListResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListResponse_Data) ProtoMessage() {}

func (x *AppListResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListResponse_Data.ProtoReflect.Descriptor instead.
func (*AppListResponse_Data) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{5, 0}
}

func (x *AppListResponse_Data) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *AppListResponse_Data) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AppListResponse_Data) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AppListResponse_Data) GetDeleted_At() *timestamppb.Timestamp {
	if x != nil {
		return x.Deleted_At
	}
	return nil
}

func (x *AppListResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppListResponse_Data) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type AppDetailResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unid       string                 `protobuf:"bytes,1,opt,name=unid,proto3" json:"unid,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deleted_At *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_At,json=deletedAt,proto3" json:"deleted_At,omitempty"`
	Name       string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Timezone   string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *AppDetailResponse_Data) Reset() {
	*x = AppDetailResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_app_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDetailResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDetailResponse_Data) ProtoMessage() {}

func (x *AppDetailResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_app_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDetailResponse_Data.ProtoReflect.Descriptor instead.
func (*AppDetailResponse_Data) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_app_proto_rawDescGZIP(), []int{7, 0}
}

func (x *AppDetailResponse_Data) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *AppDetailResponse_Data) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AppDetailResponse_Data) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AppDetailResponse_Data) GetDeleted_At() *timestamppb.Timestamp {
	if x != nil {
		return x.Deleted_At
	}
	return nil
}

func (x *AppDetailResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppDetailResponse_Data) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

var File_LinkAttributionProto_app_proto protoreflect.FileDescriptor

var file_LinkAttributionProto_app_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x4c, 0x69, 0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd0, 0x01, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x41, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x66, 0x0a, 0x11, 0x41, 0x70,
	0x70, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x6a, 0x0a, 0x15, 0x41, 0x70, 0x70, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x41, 0x70, 0x70, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x6e,
	0x0a, 0x10, 0x41, 0x70, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x55, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x22, 0x3c,
	0x0a, 0x0e, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x69, 0x64, 0x22, 0xed, 0x02, 0x0a,
	0x0f, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x1a, 0xfb,
	0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x41, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x22, 0x52, 0x0a, 0x10,
	0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x6e, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x69, 0x64,
	0x22, 0xf1, 0x02, 0x0a, 0x11, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x1a, 0xfb, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x6e, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x5f, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x7a, 0x6f, 0x6e, 0x65, 0x22, 0x3a, 0x0a, 0x18, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x42, 0x79, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x32, 0x96, 0x02, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3e, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x41, 0x70, 0x70,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x41, 0x70,
	0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x11, 0x41, 0x70, 0x70,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1e,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42,
	0x79, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LinkAttributionProto_app_proto_rawDescOnce sync.Once
	file_LinkAttributionProto_app_proto_rawDescData = file_LinkAttributionProto_app_proto_rawDesc
)

func file_LinkAttributionProto_app_proto_rawDescGZIP() []byte {
	file_LinkAttributionProto_app_proto_rawDescOnce.Do(func() {
		file_LinkAttributionProto_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_LinkAttributionProto_app_proto_rawDescData)
	})
	return file_LinkAttributionProto_app_proto_rawDescData
}

var file_LinkAttributionProto_app_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_LinkAttributionProto_app_proto_goTypes = []interface{}{
	(*AppUpsert)(nil),                // 0: chat.AppUpsert
	(*AppUpsertResponse)(nil),        // 1: chat.AppUpsertResponse
	(*AppUpsertListResponse)(nil),    // 2: chat.AppUpsertListResponse
	(*AppCreateRequest)(nil),         // 3: chat.AppCreateRequest
	(*AppListRequest)(nil),           // 4: chat.AppListRequest
	(*AppListResponse)(nil),          // 5: chat.AppListResponse
	(*AppDetailRequest)(nil),         // 6: chat.AppDetailRequest
	(*AppDetailResponse)(nil),        // 7: chat.AppDetailResponse
	(*AppDetailByDomainRequest)(nil), // 8: chat.AppDetailByDomainRequest
	(*AppListResponse_Data)(nil),     // 9: chat.AppListResponse.Data
	(*AppDetailResponse_Data)(nil),   // 10: chat.AppDetailResponse.Data
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_LinkAttributionProto_app_proto_depIdxs = []int32{
	11, // 0: chat.AppUpsert.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: chat.AppUpsert.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: chat.AppUpsert.deleted_At:type_name -> google.protobuf.Timestamp
	0,  // 3: chat.AppUpsertResponse.data:type_name -> chat.AppUpsert
	0,  // 4: chat.AppUpsertListResponse.data:type_name -> chat.AppUpsert
	9,  // 5: chat.AppListResponse.data:type_name -> chat.AppListResponse.Data
	10, // 6: chat.AppDetailResponse.data:type_name -> chat.AppDetailResponse.Data
	11, // 7: chat.AppListResponse.Data.created_at:type_name -> google.protobuf.Timestamp
	11, // 8: chat.AppListResponse.Data.updated_at:type_name -> google.protobuf.Timestamp
	11, // 9: chat.AppListResponse.Data.deleted_At:type_name -> google.protobuf.Timestamp
	11, // 10: chat.AppDetailResponse.Data.created_at:type_name -> google.protobuf.Timestamp
	11, // 11: chat.AppDetailResponse.Data.updated_at:type_name -> google.protobuf.Timestamp
	11, // 12: chat.AppDetailResponse.Data.deleted_At:type_name -> google.protobuf.Timestamp
	3,  // 13: chat.AppService.AppCreate:input_type -> chat.AppCreateRequest
	4,  // 14: chat.AppService.AppList:input_type -> chat.AppListRequest
	6,  // 15: chat.AppService.AppDetail:input_type -> chat.AppDetailRequest
	8,  // 16: chat.AppService.AppDetailByDomain:input_type -> chat.AppDetailByDomainRequest
	1,  // 17: chat.AppService.AppCreate:output_type -> chat.AppUpsertResponse
	5,  // 18: chat.AppService.AppList:output_type -> chat.AppListResponse
	7,  // 19: chat.AppService.AppDetail:output_type -> chat.AppDetailResponse
	7,  // 20: chat.AppService.AppDetailByDomain:output_type -> chat.AppDetailResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_LinkAttributionProto_app_proto_init() }
func file_LinkAttributionProto_app_proto_init() {
	if File_LinkAttributionProto_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_LinkAttributionProto_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppUpsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppUpsertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppUpsertListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDetailByDomainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppListResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_app_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDetailResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LinkAttributionProto_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_LinkAttributionProto_app_proto_goTypes,
		DependencyIndexes: file_LinkAttributionProto_app_proto_depIdxs,
		MessageInfos:      file_LinkAttributionProto_app_proto_msgTypes,
	}.Build()
	File_LinkAttributionProto_app_proto = out.File
	file_LinkAttributionProto_app_proto_rawDesc = nil
	file_LinkAttributionProto_app_proto_goTypes = nil
	file_LinkAttributionProto_app_proto_depIdxs = nil
}
