// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: LinkAttributionProto/client_session.proto

package linkAttribution

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientSessionServiceClient is the client API for ClientSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientSessionServiceClient interface {
	ClientSessionCreate(ctx context.Context, in *ClientSessionCreateRequest, opts ...grpc.CallOption) (*ClientSessionUpsertResponse, error)
}

type clientSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientSessionServiceClient(cc grpc.ClientConnInterface) ClientSessionServiceClient {
	return &clientSessionServiceClient{cc}
}

func (c *clientSessionServiceClient) ClientSessionCreate(ctx context.Context, in *ClientSessionCreateRequest, opts ...grpc.CallOption) (*ClientSessionUpsertResponse, error) {
	out := new(ClientSessionUpsertResponse)
	err := c.cc.Invoke(ctx, "/chat.ClientSessionService/ClientSessionCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientSessionServiceServer is the server API for ClientSessionService service.
// All implementations must embed UnimplementedClientSessionServiceServer
// for forward compatibility
type ClientSessionServiceServer interface {
	ClientSessionCreate(context.Context, *ClientSessionCreateRequest) (*ClientSessionUpsertResponse, error)
	mustEmbedUnimplementedClientSessionServiceServer()
}

// UnimplementedClientSessionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClientSessionServiceServer struct {
}

func (UnimplementedClientSessionServiceServer) ClientSessionCreate(context.Context, *ClientSessionCreateRequest) (*ClientSessionUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientSessionCreate not implemented")
}
func (UnimplementedClientSessionServiceServer) mustEmbedUnimplementedClientSessionServiceServer() {}

// UnsafeClientSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientSessionServiceServer will
// result in compilation errors.
type UnsafeClientSessionServiceServer interface {
	mustEmbedUnimplementedClientSessionServiceServer()
}

func RegisterClientSessionServiceServer(s grpc.ServiceRegistrar, srv ClientSessionServiceServer) {
	s.RegisterService(&ClientSessionService_ServiceDesc, srv)
}

func _ClientSessionService_ClientSessionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientSessionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientSessionServiceServer).ClientSessionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ClientSessionService/ClientSessionCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientSessionServiceServer).ClientSessionCreate(ctx, req.(*ClientSessionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientSessionService_ServiceDesc is the grpc.ServiceDesc for ClientSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ClientSessionService",
	HandlerType: (*ClientSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientSessionCreate",
			Handler:    _ClientSessionService_ClientSessionCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "LinkAttributionProto/client_session.proto",
}
