// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: LinkAttributionProto/configuration.proto

package linkAttribution

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConfigurationClient is the client API for Configuration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigurationClient interface {
	ConfigurationUpdate(ctx context.Context, in *ConfigurationUpdateRequest, opts ...grpc.CallOption) (*ConfigurationUpsertResponse, error)
	ConfigurationDetailByAppUnid(ctx context.Context, in *ConfigurationDetailByAppUnidRequest, opts ...grpc.CallOption) (*ConfigurationDetailByAppUnidResponse, error)
	ConfigurationIsExistDomain(ctx context.Context, in *ConfigurationIsExistDomainRequest, opts ...grpc.CallOption) (*ConfigurationIsExistDomainResponse, error)
}

type configurationClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationClient(cc grpc.ClientConnInterface) ConfigurationClient {
	return &configurationClient{cc}
}

func (c *configurationClient) ConfigurationUpdate(ctx context.Context, in *ConfigurationUpdateRequest, opts ...grpc.CallOption) (*ConfigurationUpsertResponse, error) {
	out := new(ConfigurationUpsertResponse)
	err := c.cc.Invoke(ctx, "/chat.Configuration/ConfigurationUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) ConfigurationDetailByAppUnid(ctx context.Context, in *ConfigurationDetailByAppUnidRequest, opts ...grpc.CallOption) (*ConfigurationDetailByAppUnidResponse, error) {
	out := new(ConfigurationDetailByAppUnidResponse)
	err := c.cc.Invoke(ctx, "/chat.Configuration/ConfigurationDetailByAppUnid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) ConfigurationIsExistDomain(ctx context.Context, in *ConfigurationIsExistDomainRequest, opts ...grpc.CallOption) (*ConfigurationIsExistDomainResponse, error) {
	out := new(ConfigurationIsExistDomainResponse)
	err := c.cc.Invoke(ctx, "/chat.Configuration/ConfigurationIsExistDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationServer is the server API for Configuration service.
// All implementations must embed UnimplementedConfigurationServer
// for forward compatibility
type ConfigurationServer interface {
	ConfigurationUpdate(context.Context, *ConfigurationUpdateRequest) (*ConfigurationUpsertResponse, error)
	ConfigurationDetailByAppUnid(context.Context, *ConfigurationDetailByAppUnidRequest) (*ConfigurationDetailByAppUnidResponse, error)
	ConfigurationIsExistDomain(context.Context, *ConfigurationIsExistDomainRequest) (*ConfigurationIsExistDomainResponse, error)
	mustEmbedUnimplementedConfigurationServer()
}

// UnimplementedConfigurationServer must be embedded to have forward compatible implementations.
type UnimplementedConfigurationServer struct {
}

func (UnimplementedConfigurationServer) ConfigurationUpdate(context.Context, *ConfigurationUpdateRequest) (*ConfigurationUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigurationUpdate not implemented")
}
func (UnimplementedConfigurationServer) ConfigurationDetailByAppUnid(context.Context, *ConfigurationDetailByAppUnidRequest) (*ConfigurationDetailByAppUnidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigurationDetailByAppUnid not implemented")
}
func (UnimplementedConfigurationServer) ConfigurationIsExistDomain(context.Context, *ConfigurationIsExistDomainRequest) (*ConfigurationIsExistDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigurationIsExistDomain not implemented")
}
func (UnimplementedConfigurationServer) mustEmbedUnimplementedConfigurationServer() {}

// UnsafeConfigurationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationServer will
// result in compilation errors.
type UnsafeConfigurationServer interface {
	mustEmbedUnimplementedConfigurationServer()
}

func RegisterConfigurationServer(s grpc.ServiceRegistrar, srv ConfigurationServer) {
	s.RegisterService(&Configuration_ServiceDesc, srv)
}

func _Configuration_ConfigurationUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).ConfigurationUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Configuration/ConfigurationUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).ConfigurationUpdate(ctx, req.(*ConfigurationUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_ConfigurationDetailByAppUnid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationDetailByAppUnidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).ConfigurationDetailByAppUnid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Configuration/ConfigurationDetailByAppUnid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).ConfigurationDetailByAppUnid(ctx, req.(*ConfigurationDetailByAppUnidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_ConfigurationIsExistDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationIsExistDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).ConfigurationIsExistDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Configuration/ConfigurationIsExistDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).ConfigurationIsExistDomain(ctx, req.(*ConfigurationIsExistDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Configuration_ServiceDesc is the grpc.ServiceDesc for Configuration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Configuration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Configuration",
	HandlerType: (*ConfigurationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigurationUpdate",
			Handler:    _Configuration_ConfigurationUpdate_Handler,
		},
		{
			MethodName: "ConfigurationDetailByAppUnid",
			Handler:    _Configuration_ConfigurationDetailByAppUnid_Handler,
		},
		{
			MethodName: "ConfigurationIsExistDomain",
			Handler:    _Configuration_ConfigurationIsExistDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "LinkAttributionProto/configuration.proto",
}
