// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: LinkAttributionProto/link.proto

package linkAttribution

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LinkServiceClient is the client API for LinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkServiceClient interface {
	LinksBulkCreate(ctx context.Context, in *LinksBulkCreateRequest, opts ...grpc.CallOption) (*LinkUpsertListResponse, error)
	LinkRemove(ctx context.Context, in *LinkRemoveRequest, opts ...grpc.CallOption) (*LinkUpsertResponse, error)
	LinkUpdate(ctx context.Context, in *Link, opts ...grpc.CallOption) (*LinkUpsertResponse, error)
	LinkGetList(ctx context.Context, in *LinkGetListRequest, opts ...grpc.CallOption) (*LinkGetListResponse, error)
	LinkGetDetailByPath(ctx context.Context, in *LinkGetDetailByPathRequest, opts ...grpc.CallOption) (*LinkDetailResponse, error)
}

type linkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkServiceClient(cc grpc.ClientConnInterface) LinkServiceClient {
	return &linkServiceClient{cc}
}

func (c *linkServiceClient) LinksBulkCreate(ctx context.Context, in *LinksBulkCreateRequest, opts ...grpc.CallOption) (*LinkUpsertListResponse, error) {
	out := new(LinkUpsertListResponse)
	err := c.cc.Invoke(ctx, "/chat.LinkService/LinksBulkCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) LinkRemove(ctx context.Context, in *LinkRemoveRequest, opts ...grpc.CallOption) (*LinkUpsertResponse, error) {
	out := new(LinkUpsertResponse)
	err := c.cc.Invoke(ctx, "/chat.LinkService/LinkRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) LinkUpdate(ctx context.Context, in *Link, opts ...grpc.CallOption) (*LinkUpsertResponse, error) {
	out := new(LinkUpsertResponse)
	err := c.cc.Invoke(ctx, "/chat.LinkService/LinkUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) LinkGetList(ctx context.Context, in *LinkGetListRequest, opts ...grpc.CallOption) (*LinkGetListResponse, error) {
	out := new(LinkGetListResponse)
	err := c.cc.Invoke(ctx, "/chat.LinkService/LinkGetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) LinkGetDetailByPath(ctx context.Context, in *LinkGetDetailByPathRequest, opts ...grpc.CallOption) (*LinkDetailResponse, error) {
	out := new(LinkDetailResponse)
	err := c.cc.Invoke(ctx, "/chat.LinkService/LinkGetDetailByPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServiceServer is the server API for LinkService service.
// All implementations must embed UnimplementedLinkServiceServer
// for forward compatibility
type LinkServiceServer interface {
	LinksBulkCreate(context.Context, *LinksBulkCreateRequest) (*LinkUpsertListResponse, error)
	LinkRemove(context.Context, *LinkRemoveRequest) (*LinkUpsertResponse, error)
	LinkUpdate(context.Context, *Link) (*LinkUpsertResponse, error)
	LinkGetList(context.Context, *LinkGetListRequest) (*LinkGetListResponse, error)
	LinkGetDetailByPath(context.Context, *LinkGetDetailByPathRequest) (*LinkDetailResponse, error)
	mustEmbedUnimplementedLinkServiceServer()
}

// UnimplementedLinkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLinkServiceServer struct {
}

func (UnimplementedLinkServiceServer) LinksBulkCreate(context.Context, *LinksBulkCreateRequest) (*LinkUpsertListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinksBulkCreate not implemented")
}
func (UnimplementedLinkServiceServer) LinkRemove(context.Context, *LinkRemoveRequest) (*LinkUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkRemove not implemented")
}
func (UnimplementedLinkServiceServer) LinkUpdate(context.Context, *Link) (*LinkUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkUpdate not implemented")
}
func (UnimplementedLinkServiceServer) LinkGetList(context.Context, *LinkGetListRequest) (*LinkGetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkGetList not implemented")
}
func (UnimplementedLinkServiceServer) LinkGetDetailByPath(context.Context, *LinkGetDetailByPathRequest) (*LinkDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkGetDetailByPath not implemented")
}
func (UnimplementedLinkServiceServer) mustEmbedUnimplementedLinkServiceServer() {}

// UnsafeLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkServiceServer will
// result in compilation errors.
type UnsafeLinkServiceServer interface {
	mustEmbedUnimplementedLinkServiceServer()
}

func RegisterLinkServiceServer(s grpc.ServiceRegistrar, srv LinkServiceServer) {
	s.RegisterService(&LinkService_ServiceDesc, srv)
}

func _LinkService_LinksBulkCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinksBulkCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).LinksBulkCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.LinkService/LinksBulkCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).LinksBulkCreate(ctx, req.(*LinksBulkCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_LinkRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).LinkRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.LinkService/LinkRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).LinkRemove(ctx, req.(*LinkRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_LinkUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Link)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).LinkUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.LinkService/LinkUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).LinkUpdate(ctx, req.(*Link))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_LinkGetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkGetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).LinkGetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.LinkService/LinkGetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).LinkGetList(ctx, req.(*LinkGetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_LinkGetDetailByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkGetDetailByPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).LinkGetDetailByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.LinkService/LinkGetDetailByPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).LinkGetDetailByPath(ctx, req.(*LinkGetDetailByPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkService_ServiceDesc is the grpc.ServiceDesc for LinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.LinkService",
	HandlerType: (*LinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LinksBulkCreate",
			Handler:    _LinkService_LinksBulkCreate_Handler,
		},
		{
			MethodName: "LinkRemove",
			Handler:    _LinkService_LinkRemove_Handler,
		},
		{
			MethodName: "LinkUpdate",
			Handler:    _LinkService_LinkUpdate_Handler,
		},
		{
			MethodName: "LinkGetList",
			Handler:    _LinkService_LinkGetList_Handler,
		},
		{
			MethodName: "LinkGetDetailByPath",
			Handler:    _LinkService_LinkGetDetailByPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "LinkAttributionProto/link.proto",
}
