// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: LinkAttributionProto/link.proto

package linkAttribution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkUpsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unid       string                 `protobuf:"bytes,1,opt,name=unid,proto3" json:"unid,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deleted_At *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_At,json=deletedAt,proto3" json:"deleted_At,omitempty"`
}

func (x *LinkUpsert) Reset() {
	*x = LinkUpsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpsert) ProtoMessage() {}

func (x *LinkUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpsert.ProtoReflect.Descriptor instead.
func (*LinkUpsert) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{0}
}

func (x *LinkUpsert) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *LinkUpsert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LinkUpsert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *LinkUpsert) GetDeleted_At() *timestamppb.Timestamp {
	if x != nil {
		return x.Deleted_At
	}
	return nil
}

type LinkUpsertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *LinkUpsert `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32       `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LinkUpsertResponse) Reset() {
	*x = LinkUpsertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkUpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpsertResponse) ProtoMessage() {}

func (x *LinkUpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpsertResponse.ProtoReflect.Descriptor instead.
func (*LinkUpsertResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{1}
}

func (x *LinkUpsertResponse) GetData() *LinkUpsert {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LinkUpsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LinkUpsertResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LinkUpsertListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []*LinkUpsert `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32         `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LinkUpsertListResponse) Reset() {
	*x = LinkUpsertListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkUpsertListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpsertListResponse) ProtoMessage() {}

func (x *LinkUpsertListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpsertListResponse.ProtoReflect.Descriptor instead.
func (*LinkUpsertListResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{2}
}

func (x *LinkUpsertListResponse) GetData() []*LinkUpsert {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LinkUpsertListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LinkUpsertListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LinksBulkCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links []*LinksBulkCreateRequest_LinksCreate `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *LinksBulkCreateRequest) Reset() {
	*x = LinksBulkCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinksBulkCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksBulkCreateRequest) ProtoMessage() {}

func (x *LinksBulkCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksBulkCreateRequest.ProtoReflect.Descriptor instead.
func (*LinksBulkCreateRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{3}
}

func (x *LinksBulkCreateRequest) GetLinks() []*LinksBulkCreateRequest_LinksCreate {
	if x != nil {
		return x.Links
	}
	return nil
}

type LinksBulkCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *LinkUpsert `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32       `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LinksBulkCreateResponse) Reset() {
	*x = LinksBulkCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinksBulkCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksBulkCreateResponse) ProtoMessage() {}

func (x *LinksBulkCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksBulkCreateResponse.ProtoReflect.Descriptor instead.
func (*LinksBulkCreateResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{4}
}

func (x *LinksBulkCreateResponse) GetData() *LinkUpsert {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LinksBulkCreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LinksBulkCreateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LinksBulkCreateRequest_AnalyticsTags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Feature  string   `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Channel  string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Campaign string   `protobuf:"bytes,3,opt,name=campaign,proto3" json:"campaign,omitempty"`
	Tags     []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *LinksBulkCreateRequest_AnalyticsTags) Reset() {
	*x = LinksBulkCreateRequest_AnalyticsTags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinksBulkCreateRequest_AnalyticsTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksBulkCreateRequest_AnalyticsTags) ProtoMessage() {}

func (x *LinksBulkCreateRequest_AnalyticsTags) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksBulkCreateRequest_AnalyticsTags.ProtoReflect.Descriptor instead.
func (*LinksBulkCreateRequest_AnalyticsTags) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{3, 0}
}

func (x *LinksBulkCreateRequest_AnalyticsTags) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *LinksBulkCreateRequest_AnalyticsTags) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *LinksBulkCreateRequest_AnalyticsTags) GetCampaign() string {
	if x != nil {
		return x.Campaign
	}
	return ""
}

func (x *LinksBulkCreateRequest_AnalyticsTags) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type LinksBulkCreateRequest_SocialMediaPreview struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *LinksBulkCreateRequest_SocialMediaPreview) Reset() {
	*x = LinksBulkCreateRequest_SocialMediaPreview{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinksBulkCreateRequest_SocialMediaPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksBulkCreateRequest_SocialMediaPreview) ProtoMessage() {}

func (x *LinksBulkCreateRequest_SocialMediaPreview) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksBulkCreateRequest_SocialMediaPreview.ProtoReflect.Descriptor instead.
func (*LinksBulkCreateRequest_SocialMediaPreview) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{3, 1}
}

func (x *LinksBulkCreateRequest_SocialMediaPreview) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LinksBulkCreateRequest_SocialMediaPreview) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type LinksBulkCreateRequest_LinksCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppUnid            string                                     `protobuf:"bytes,1,opt,name=appUnid,proto3" json:"appUnid,omitempty"`
	Type               string                                     `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name               string                                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path               string                                     `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	AnalyticsTags      *LinksBulkCreateRequest_AnalyticsTags      `protobuf:"bytes,5,opt,name=analyticsTags,proto3" json:"analyticsTags,omitempty"`
	LinkData           *anypb.Any                                 `protobuf:"bytes,6,opt,name=linkData,proto3" json:"linkData,omitempty"`
	IosRedirect        string                                     `protobuf:"bytes,7,opt,name=iosRedirect,proto3" json:"iosRedirect,omitempty"`
	AndroidRedirect    string                                     `protobuf:"bytes,8,opt,name=androidRedirect,proto3" json:"androidRedirect,omitempty"`
	IsWebOnly          bool                                       `protobuf:"varint,9,opt,name=isWebOnly,proto3" json:"isWebOnly,omitempty"`
	SocialMediaPreview *LinksBulkCreateRequest_SocialMediaPreview `protobuf:"bytes,10,opt,name=socialMediaPreview,proto3" json:"socialMediaPreview,omitempty"`
}

func (x *LinksBulkCreateRequest_LinksCreate) Reset() {
	*x = LinksBulkCreateRequest_LinksCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinksBulkCreateRequest_LinksCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksBulkCreateRequest_LinksCreate) ProtoMessage() {}

func (x *LinksBulkCreateRequest_LinksCreate) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksBulkCreateRequest_LinksCreate.ProtoReflect.Descriptor instead.
func (*LinksBulkCreateRequest_LinksCreate) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{3, 2}
}

func (x *LinksBulkCreateRequest_LinksCreate) GetAppUnid() string {
	if x != nil {
		return x.AppUnid
	}
	return ""
}

func (x *LinksBulkCreateRequest_LinksCreate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LinksBulkCreateRequest_LinksCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinksBulkCreateRequest_LinksCreate) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LinksBulkCreateRequest_LinksCreate) GetAnalyticsTags() *LinksBulkCreateRequest_AnalyticsTags {
	if x != nil {
		return x.AnalyticsTags
	}
	return nil
}

func (x *LinksBulkCreateRequest_LinksCreate) GetLinkData() *anypb.Any {
	if x != nil {
		return x.LinkData
	}
	return nil
}

func (x *LinksBulkCreateRequest_LinksCreate) GetIosRedirect() string {
	if x != nil {
		return x.IosRedirect
	}
	return ""
}

func (x *LinksBulkCreateRequest_LinksCreate) GetAndroidRedirect() string {
	if x != nil {
		return x.AndroidRedirect
	}
	return ""
}

func (x *LinksBulkCreateRequest_LinksCreate) GetIsWebOnly() bool {
	if x != nil {
		return x.IsWebOnly
	}
	return false
}

func (x *LinksBulkCreateRequest_LinksCreate) GetSocialMediaPreview() *LinksBulkCreateRequest_SocialMediaPreview {
	if x != nil {
		return x.SocialMediaPreview
	}
	return nil
}

var File_LinkAttributionProto_link_proto protoreflect.FileDescriptor

var file_LinkAttributionProto_link_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x4c, 0x69, 0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x01, 0x0a, 0x0a, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x68, 0x0a, 0x12, 0x4c, 0x69, 0x6e, 0x6b, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x6c, 0x0a, 0x16, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0xd0, 0x05, 0x0a, 0x16, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x05, 0x6c, 0x69,
	0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x1a, 0x73, 0x0a, 0x0d, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x54, 0x61, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a,
	0x4c, 0x0a, 0x12, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x50, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xb2, 0x03,
	0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x50, 0x0a, 0x0d, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x54, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69,
	0x63, 0x73, 0x54, 0x61, 0x67, 0x73, 0x52, 0x0d, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63,
	0x73, 0x54, 0x61, 0x67, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x6c,
	0x69, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6f, 0x73, 0x52, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6f,
	0x73, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x52, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x57, 0x65, 0x62, 0x4f, 0x6e, 0x6c, 0x79,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x57, 0x65, 0x62, 0x4f, 0x6e, 0x6c,
	0x79, 0x12, 0x5f, 0x0a, 0x12, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x12,
	0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x50, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x22, 0x6d, 0x0a, 0x17, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x32, 0x5e, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4f, 0x0a, 0x0f, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73,
	0x42, 0x75, 0x6c, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1a, 0x5a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x6c, 0x69,
	0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LinkAttributionProto_link_proto_rawDescOnce sync.Once
	file_LinkAttributionProto_link_proto_rawDescData = file_LinkAttributionProto_link_proto_rawDesc
)

func file_LinkAttributionProto_link_proto_rawDescGZIP() []byte {
	file_LinkAttributionProto_link_proto_rawDescOnce.Do(func() {
		file_LinkAttributionProto_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_LinkAttributionProto_link_proto_rawDescData)
	})
	return file_LinkAttributionProto_link_proto_rawDescData
}

var file_LinkAttributionProto_link_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_LinkAttributionProto_link_proto_goTypes = []interface{}{
	(*LinkUpsert)(nil),                                // 0: chat.LinkUpsert
	(*LinkUpsertResponse)(nil),                        // 1: chat.LinkUpsertResponse
	(*LinkUpsertListResponse)(nil),                    // 2: chat.LinkUpsertListResponse
	(*LinksBulkCreateRequest)(nil),                    // 3: chat.LinksBulkCreateRequest
	(*LinksBulkCreateResponse)(nil),                   // 4: chat.LinksBulkCreateResponse
	(*LinksBulkCreateRequest_AnalyticsTags)(nil),      // 5: chat.LinksBulkCreateRequest.AnalyticsTags
	(*LinksBulkCreateRequest_SocialMediaPreview)(nil), // 6: chat.LinksBulkCreateRequest.SocialMediaPreview
	(*LinksBulkCreateRequest_LinksCreate)(nil),        // 7: chat.LinksBulkCreateRequest.LinksCreate
	(*timestamppb.Timestamp)(nil),                     // 8: google.protobuf.Timestamp
	(*anypb.Any)(nil),                                 // 9: google.protobuf.Any
}
var file_LinkAttributionProto_link_proto_depIdxs = []int32{
	8,  // 0: chat.LinkUpsert.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: chat.LinkUpsert.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: chat.LinkUpsert.deleted_At:type_name -> google.protobuf.Timestamp
	0,  // 3: chat.LinkUpsertResponse.data:type_name -> chat.LinkUpsert
	0,  // 4: chat.LinkUpsertListResponse.data:type_name -> chat.LinkUpsert
	7,  // 5: chat.LinksBulkCreateRequest.links:type_name -> chat.LinksBulkCreateRequest.LinksCreate
	0,  // 6: chat.LinksBulkCreateResponse.data:type_name -> chat.LinkUpsert
	5,  // 7: chat.LinksBulkCreateRequest.LinksCreate.analyticsTags:type_name -> chat.LinksBulkCreateRequest.AnalyticsTags
	9,  // 8: chat.LinksBulkCreateRequest.LinksCreate.linkData:type_name -> google.protobuf.Any
	6,  // 9: chat.LinksBulkCreateRequest.LinksCreate.socialMediaPreview:type_name -> chat.LinksBulkCreateRequest.SocialMediaPreview
	3,  // 10: chat.LinkService.LinksBulkCreate:input_type -> chat.LinksBulkCreateRequest
	2,  // 11: chat.LinkService.LinksBulkCreate:output_type -> chat.LinkUpsertListResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_LinkAttributionProto_link_proto_init() }
func file_LinkAttributionProto_link_proto_init() {
	if File_LinkAttributionProto_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_LinkAttributionProto_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkUpsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkUpsertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkUpsertListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinksBulkCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinksBulkCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinksBulkCreateRequest_AnalyticsTags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinksBulkCreateRequest_SocialMediaPreview); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinksBulkCreateRequest_LinksCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LinkAttributionProto_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_LinkAttributionProto_link_proto_goTypes,
		DependencyIndexes: file_LinkAttributionProto_link_proto_depIdxs,
		MessageInfos:      file_LinkAttributionProto_link_proto_msgTypes,
	}.Build()
	File_LinkAttributionProto_link_proto = out.File
	file_LinkAttributionProto_link_proto_rawDesc = nil
	file_LinkAttributionProto_link_proto_goTypes = nil
	file_LinkAttributionProto_link_proto_depIdxs = nil
}
