// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: LinkAttributionProto/link.proto

package linkAttribution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkUpsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unid      string                 `protobuf:"bytes,1,opt,name=unid,proto3" json:"unid,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
}

func (x *LinkUpsert) Reset() {
	*x = LinkUpsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpsert) ProtoMessage() {}

func (x *LinkUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpsert.ProtoReflect.Descriptor instead.
func (*LinkUpsert) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{0}
}

func (x *LinkUpsert) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *LinkUpsert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LinkUpsert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *LinkUpsert) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type LinkUpsertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *LinkUpsert `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32       `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LinkUpsertResponse) Reset() {
	*x = LinkUpsertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkUpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpsertResponse) ProtoMessage() {}

func (x *LinkUpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpsertResponse.ProtoReflect.Descriptor instead.
func (*LinkUpsertResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{1}
}

func (x *LinkUpsertResponse) GetData() *LinkUpsert {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LinkUpsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LinkUpsertResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LinkUpsertListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []*LinkUpsert `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32         `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LinkUpsertListResponse) Reset() {
	*x = LinkUpsertListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkUpsertListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpsertListResponse) ProtoMessage() {}

func (x *LinkUpsertListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpsertListResponse.ProtoReflect.Descriptor instead.
func (*LinkUpsertListResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{2}
}

func (x *LinkUpsertListResponse) GetData() []*LinkUpsert {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LinkUpsertListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LinkUpsertListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type               string                   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name               string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Path               string                   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	AnalyticsTags      *Link_AnalyticsTags      `protobuf:"bytes,5,opt,name=analyticsTags,proto3" json:"analyticsTags,omitempty"`
	Attributes         string                   `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	SocialMediaPreview *Link_SocialMediaPreview `protobuf:"bytes,7,opt,name=socialMediaPreview,proto3" json:"socialMediaPreview,omitempty"`
	AppUnid            string                   `protobuf:"bytes,8,opt,name=appUnid,proto3" json:"appUnid,omitempty"`
	Unid               string                   `protobuf:"bytes,9,opt,name=unid,proto3" json:"unid,omitempty"`
	CreatedAt          *timestamppb.Timestamp   `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt          *timestamppb.Timestamp   `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt          *timestamppb.Timestamp   `protobuf:"bytes,12,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{3}
}

func (x *Link) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Link) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Link) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Link) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Link) GetAnalyticsTags() *Link_AnalyticsTags {
	if x != nil {
		return x.AnalyticsTags
	}
	return nil
}

func (x *Link) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *Link) GetSocialMediaPreview() *Link_SocialMediaPreview {
	if x != nil {
		return x.SocialMediaPreview
	}
	return nil
}

func (x *Link) GetAppUnid() string {
	if x != nil {
		return x.AppUnid
	}
	return ""
}

func (x *Link) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *Link) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Link) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Link) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type LinksBulkCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppUnid string  `protobuf:"bytes,1,opt,name=appUnid,proto3" json:"appUnid,omitempty"`
	Links   []*Link `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *LinksBulkCreateRequest) Reset() {
	*x = LinksBulkCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinksBulkCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksBulkCreateRequest) ProtoMessage() {}

func (x *LinksBulkCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksBulkCreateRequest.ProtoReflect.Descriptor instead.
func (*LinksBulkCreateRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{4}
}

func (x *LinksBulkCreateRequest) GetAppUnid() string {
	if x != nil {
		return x.AppUnid
	}
	return ""
}

func (x *LinksBulkCreateRequest) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type LinksBulkCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *LinkUpsert `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32       `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LinksBulkCreateResponse) Reset() {
	*x = LinksBulkCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinksBulkCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksBulkCreateResponse) ProtoMessage() {}

func (x *LinksBulkCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksBulkCreateResponse.ProtoReflect.Descriptor instead.
func (*LinksBulkCreateResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{5}
}

func (x *LinksBulkCreateResponse) GetData() *LinkUpsert {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LinksBulkCreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LinksBulkCreateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LinkRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unid    string `protobuf:"bytes,1,opt,name=unid,proto3" json:"unid,omitempty"`
	AppUnid string `protobuf:"bytes,2,opt,name=appUnid,proto3" json:"appUnid,omitempty"`
}

func (x *LinkRemoveRequest) Reset() {
	*x = LinkRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRemoveRequest) ProtoMessage() {}

func (x *LinkRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRemoveRequest.ProtoReflect.Descriptor instead.
func (*LinkRemoveRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{6}
}

func (x *LinkRemoveRequest) GetUnid() string {
	if x != nil {
		return x.Unid
	}
	return ""
}

func (x *LinkRemoveRequest) GetAppUnid() string {
	if x != nil {
		return x.AppUnid
	}
	return ""
}

type LinkGetListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppUnid string `protobuf:"bytes,1,opt,name=appUnid,proto3" json:"appUnid,omitempty"`
	Limit   uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset  uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *LinkGetListRequest) Reset() {
	*x = LinkGetListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkGetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGetListRequest) ProtoMessage() {}

func (x *LinkGetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGetListRequest.ProtoReflect.Descriptor instead.
func (*LinkGetListRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{7}
}

func (x *LinkGetListRequest) GetAppUnid() string {
	if x != nil {
		return x.AppUnid
	}
	return ""
}

func (x *LinkGetListRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LinkGetListRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type LinkGetListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Link `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *LinkGetListResponse) Reset() {
	*x = LinkGetListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGetListResponse) ProtoMessage() {}

func (x *LinkGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGetListResponse.ProtoReflect.Descriptor instead.
func (*LinkGetListResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{8}
}

func (x *LinkGetListResponse) GetData() []*Link {
	if x != nil {
		return x.Data
	}
	return nil
}

type LinkGetDetailByPathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppUnid string `protobuf:"bytes,1,opt,name=appUnid,proto3" json:"appUnid,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *LinkGetDetailByPathRequest) Reset() {
	*x = LinkGetDetailByPathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkGetDetailByPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGetDetailByPathRequest) ProtoMessage() {}

func (x *LinkGetDetailByPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGetDetailByPathRequest.ProtoReflect.Descriptor instead.
func (*LinkGetDetailByPathRequest) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{9}
}

func (x *LinkGetDetailByPathRequest) GetAppUnid() string {
	if x != nil {
		return x.AppUnid
	}
	return ""
}

func (x *LinkGetDetailByPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LinkDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Link `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LinkDetailResponse) Reset() {
	*x = LinkDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkDetailResponse) ProtoMessage() {}

func (x *LinkDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkDetailResponse.ProtoReflect.Descriptor instead.
func (*LinkDetailResponse) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{10}
}

func (x *LinkDetailResponse) GetData() *Link {
	if x != nil {
		return x.Data
	}
	return nil
}

type Link_AnalyticsTags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Feature  string   `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Channel  string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Campaign string   `protobuf:"bytes,3,opt,name=campaign,proto3" json:"campaign,omitempty"`
	Tags     []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Link_AnalyticsTags) Reset() {
	*x = Link_AnalyticsTags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link_AnalyticsTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link_AnalyticsTags) ProtoMessage() {}

func (x *Link_AnalyticsTags) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link_AnalyticsTags.ProtoReflect.Descriptor instead.
func (*Link_AnalyticsTags) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Link_AnalyticsTags) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *Link_AnalyticsTags) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Link_AnalyticsTags) GetCampaign() string {
	if x != nil {
		return x.Campaign
	}
	return ""
}

func (x *Link_AnalyticsTags) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Link_SocialMediaPreview struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Link_SocialMediaPreview) Reset() {
	*x = Link_SocialMediaPreview{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LinkAttributionProto_link_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link_SocialMediaPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link_SocialMediaPreview) ProtoMessage() {}

func (x *Link_SocialMediaPreview) ProtoReflect() protoreflect.Message {
	mi := &file_LinkAttributionProto_link_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link_SocialMediaPreview.ProtoReflect.Descriptor instead.
func (*Link_SocialMediaPreview) Descriptor() ([]byte, []int) {
	return file_LinkAttributionProto_link_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Link_SocialMediaPreview) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Link_SocialMediaPreview) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_LinkAttributionProto_link_proto protoreflect.FileDescriptor

var file_LinkAttributionProto_link_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x4c, 0x69, 0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xce, 0x01, 0x0a, 0x0a, 0x4c, 0x69, 0x6e,
	0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x38, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x68, 0x0a, 0x12, 0x4c, 0x69, 0x6e,
	0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x6c, 0x0a, 0x16, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65, 0x72,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0xb2, 0x05, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x3e, 0x0a, 0x0d, 0x61, 0x6e, 0x61, 0x6c,
	0x79, 0x74, 0x69, 0x63, 0x73, 0x54, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x74, 0x69, 0x63, 0x73, 0x54, 0x61, 0x67, 0x73, 0x52, 0x0d, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x74, 0x69, 0x63, 0x73, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x4d, 0x0a, 0x12, 0x73, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b,
	0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x50, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x52, 0x12, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e,
	0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x6e, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x1a, 0x73, 0x0a, 0x0d, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x54, 0x61, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x4c, 0x0a, 0x12, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x54, 0x0a, 0x16, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42,
	0x75, 0x6c, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x6c, 0x69,
	0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x6d, 0x0a, 0x17,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e,
	0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x41, 0x0a, 0x11, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x6e, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x22, 0x5c,
	0x0a, 0x12, 0x4c, 0x69, 0x6e, 0x6b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x35, 0x0a, 0x13,
	0x4c, 0x69, 0x6e, 0x6b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x1a, 0x4c, 0x69, 0x6e, 0x6b, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x34, 0x0a, 0x12, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xf2, 0x02, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0f, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x75,
	0x6c, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69,
	0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x17, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0a, 0x4c, 0x69, 0x6e,
	0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c,
	0x69, 0x6e, 0x6b, 0x1a, 0x18, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x44, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x13, 0x4c, 0x69, 0x6e, 0x6b, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x20, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LinkAttributionProto_link_proto_rawDescOnce sync.Once
	file_LinkAttributionProto_link_proto_rawDescData = file_LinkAttributionProto_link_proto_rawDesc
)

func file_LinkAttributionProto_link_proto_rawDescGZIP() []byte {
	file_LinkAttributionProto_link_proto_rawDescOnce.Do(func() {
		file_LinkAttributionProto_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_LinkAttributionProto_link_proto_rawDescData)
	})
	return file_LinkAttributionProto_link_proto_rawDescData
}

var file_LinkAttributionProto_link_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_LinkAttributionProto_link_proto_goTypes = []interface{}{
	(*LinkUpsert)(nil),                 // 0: chat.LinkUpsert
	(*LinkUpsertResponse)(nil),         // 1: chat.LinkUpsertResponse
	(*LinkUpsertListResponse)(nil),     // 2: chat.LinkUpsertListResponse
	(*Link)(nil),                       // 3: chat.Link
	(*LinksBulkCreateRequest)(nil),     // 4: chat.LinksBulkCreateRequest
	(*LinksBulkCreateResponse)(nil),    // 5: chat.LinksBulkCreateResponse
	(*LinkRemoveRequest)(nil),          // 6: chat.LinkRemoveRequest
	(*LinkGetListRequest)(nil),         // 7: chat.LinkGetListRequest
	(*LinkGetListResponse)(nil),        // 8: chat.LinkGetListResponse
	(*LinkGetDetailByPathRequest)(nil), // 9: chat.LinkGetDetailByPathRequest
	(*LinkDetailResponse)(nil),         // 10: chat.LinkDetailResponse
	(*Link_AnalyticsTags)(nil),         // 11: chat.Link.AnalyticsTags
	(*Link_SocialMediaPreview)(nil),    // 12: chat.Link.SocialMediaPreview
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_LinkAttributionProto_link_proto_depIdxs = []int32{
	13, // 0: chat.LinkUpsert.createdAt:type_name -> google.protobuf.Timestamp
	13, // 1: chat.LinkUpsert.updatedAt:type_name -> google.protobuf.Timestamp
	13, // 2: chat.LinkUpsert.deletedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: chat.LinkUpsertResponse.data:type_name -> chat.LinkUpsert
	0,  // 4: chat.LinkUpsertListResponse.data:type_name -> chat.LinkUpsert
	11, // 5: chat.Link.analyticsTags:type_name -> chat.Link.AnalyticsTags
	12, // 6: chat.Link.socialMediaPreview:type_name -> chat.Link.SocialMediaPreview
	13, // 7: chat.Link.createdAt:type_name -> google.protobuf.Timestamp
	13, // 8: chat.Link.updatedAt:type_name -> google.protobuf.Timestamp
	13, // 9: chat.Link.deletedAt:type_name -> google.protobuf.Timestamp
	3,  // 10: chat.LinksBulkCreateRequest.links:type_name -> chat.Link
	0,  // 11: chat.LinksBulkCreateResponse.data:type_name -> chat.LinkUpsert
	3,  // 12: chat.LinkGetListResponse.data:type_name -> chat.Link
	3,  // 13: chat.LinkDetailResponse.data:type_name -> chat.Link
	4,  // 14: chat.LinkService.LinksBulkCreate:input_type -> chat.LinksBulkCreateRequest
	6,  // 15: chat.LinkService.LinkRemove:input_type -> chat.LinkRemoveRequest
	3,  // 16: chat.LinkService.LinkUpdate:input_type -> chat.Link
	7,  // 17: chat.LinkService.LinkGetList:input_type -> chat.LinkGetListRequest
	9,  // 18: chat.LinkService.LinkGetDetailByPath:input_type -> chat.LinkGetDetailByPathRequest
	2,  // 19: chat.LinkService.LinksBulkCreate:output_type -> chat.LinkUpsertListResponse
	1,  // 20: chat.LinkService.LinkRemove:output_type -> chat.LinkUpsertResponse
	1,  // 21: chat.LinkService.LinkUpdate:output_type -> chat.LinkUpsertResponse
	8,  // 22: chat.LinkService.LinkGetList:output_type -> chat.LinkGetListResponse
	10, // 23: chat.LinkService.LinkGetDetailByPath:output_type -> chat.LinkDetailResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_LinkAttributionProto_link_proto_init() }
func file_LinkAttributionProto_link_proto_init() {
	if File_LinkAttributionProto_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_LinkAttributionProto_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkUpsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkUpsertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkUpsertListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinksBulkCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinksBulkCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkGetListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkGetListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkGetDetailByPathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link_AnalyticsTags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LinkAttributionProto_link_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link_SocialMediaPreview); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LinkAttributionProto_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_LinkAttributionProto_link_proto_goTypes,
		DependencyIndexes: file_LinkAttributionProto_link_proto_depIdxs,
		MessageInfos:      file_LinkAttributionProto_link_proto_msgTypes,
	}.Build()
	File_LinkAttributionProto_link_proto = out.File
	file_LinkAttributionProto_link_proto_rawDesc = nil
	file_LinkAttributionProto_link_proto_goTypes = nil
	file_LinkAttributionProto_link_proto_depIdxs = nil
}
